#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Italo Lelis
# Short bio or description (displayed in the header)
description: Engineering Student @ UFMG


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/5404234?v=4&u=8959d443cfbdcd4a2172be7d9f4c6a2941393d14&s=400

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: italohdc
  flickr:
  github: italohdc
  instagram: italohdc
  linkedin: italoleliscarvalho
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: italohdc
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/hdcitalohdc # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: italohdc

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-105791948-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://italolelis.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /posts/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Google SEO
# author: Italo Lelis
lang: en_US
social:
  # name: Italo Lelis
  links:
    - https://twitter.com/italohdc
    - https://www.facebook.com/italohdc
    - https://www.linkedin.com/in/italoleliscarvalho/
    - https://plus.google.com/+ItaloLelis
    - https://github.com/italohdc
# logo: https://avatars0.githubusercontent.com/u/5404234?v=4&u=8959d443cfbdcd4a2172be7d9f4c6a2941393d14&s=400
# descriptionSEO: Personal Blog. Italo Lelis is an Engineering Student at UFMG. Awarded prizes in many robotics competitions, either national and international, is in love with developing and coding.

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
